jasypt:
  encryptor:
    password: koushenhai5201314wumeihua

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: @pom.parent.artifactId@
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体类扫描，多个package用头号或分号分隔
  type-aliases-package: org.laokou.generator.server.entity
  configuration:
    log-impl: @mybatis-plus.log-impl@