spring:
  rabbitmq:
    addresses: 192.168.62.128:5672
    cache:
      channel:
        checkout-timeout: 5000
        size: 100
      connection:
        size: 10
    connection-timeout: 15000
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
      simple:
        acknowledge-mode: manual
    password: koushenhai123456
    publisher-returns: true
    username: root
    virtual-host: /
    publisher-confirm-type: correlated