server:
  port: 9999
  address: 10.0.8.7
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    session:
      cookie:
        http-only: true
    connection-timeout: 18000000

app:
  id: admin # 应用全局唯一的身份标识
apollo:
  cacheDir: /opt/config # 自定义本地配置文件缓存路径
  bootstrap:
    namespace: dynamic-tp-apollo-dtp.yml,application,applicaiton.yml
    enabled: true # 设置在应用启动阶段就加载 Apollo 配置
    eagerLoad:
      enabled: true

spring:
  boot:
    admin:
      client:
        url: http://124.222.196.51:5000/monitor
        username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
        password: ENC(nj35dMcOWEmR5EASEZR3yfaT4IdT9TPm)
        instance:
          service-base-url: http://175.178.69.253:${server.port}
          prefer-ip: true
  redis:
    database: 0
    host: 124.222.196.51
    port: 6379
    password: ENC(AHdloD6Rp4bu9SYZJbO7bcwErNCQm43R1b4zh6x4B10=)
    timeout: 6000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示无极限）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空间连接
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://124.222.196.51:3306/kcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
      password: ENC(AHdloD6Rp4bu9SYZJbO7bcwErNCQm43R1b4zh6x4B10=)
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
        url-pattern: /**
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
        login-password: ENC(nj35dMcOWEmR5EASEZR3yfaT4IdT9TPm)
        allow:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

logging:
  file:
    name: /opt/logs/${spring.application.name}/error.log

fdfs:
  connect-timeout: 6000
  so-timeout: 600000
  tracker-list: 124.222.196.51:22122

dynamic:
  datasource:
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://124.222.196.51:3306/kcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
      password: ENC(AHdloD6Rp4bu9SYZJbO7bcwErNCQm43R1b4zh6x4B10=)

service:
  elasticsearch:
    uri: 39.108.96.111:5556/elasticsearch
