server:
  port: 10004
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true
rocketmq:
  name-server: 192.168.62.137:9876
  # 生产者
  producer:
    group: laokou-producer-group
logging:
  file:
    name: /opt/logs/${spring.application.name}/info.log