server:
  port: 10004
  address: 127.0.0.1
rocketmq:
  name-server: 127.0.0.1:9876
  # 生产者
  producer:
    group: laokou-rocketmq-group
logging:
  file:
    name: logs/${spring.application.name}/info.log