server:
  port: 5000
  servlet:
    context-path: /monitor
  tomcat:
    max-connections: -1
    connection-timeout: 600000
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true
spring:
  profiles:
    active: @profile.active@
  application:
    name: @artifactId@
  security:
    user:
      name: root
      password: koushenhai

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always