jasypt:
  encryptor:
    password: koushenhai5201314wumeihua

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: @profile.active@
  application:
    name: laokou-ump
  messages:
    encoding: UTF-8
    basename: i18n/messages

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

auth:
  client_id: client_auth
  client_secret: secret
  redirect_uri: http://192.168.62.1:5555/auth/sys/loading.html
  grant_type: authorization_code

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000