server:
  port: 9002
  address: 127.0.0.1

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:5000/monitor
        username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
        password: ENC(nj35dMcOWEmR5EASEZR3yfaT4IdT9TPm)
        instance:
          service-base-url: http://127.0.0.1:${server.port}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示无极限）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空间连接
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/kcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
      password: ENC(SX9kPzLDaZb9kGOl2QBziw==)
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
        url-pattern: /**
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
        login-password: ENC(nj35dMcOWEmR5EASEZR3yfaT4IdT9TPm)
        allow:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

dynamic:
  datasource:
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/kcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
      password: ENC(SX9kPzLDaZb9kGOl2QBziw==)

logging:
  file:
    name: logs/${spring.application.name}/info.log

app:
  id: cas # 应用全局唯一的身份标识
apollo:
  cacheDir: config # 自定义本地配置文件缓存路径
  bootstrap:
    enabled: true # 设置在应用启动阶段就加载 Apollo 配置
    eagerLoad:
      enabled: true