spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: laokou-elasticsearch
  profiles:
    active: @profile.active@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always