spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: @pom.parent.artifactId@
  profiles:
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always