version: '3.8'
services:
  laokou-gateway-service:
    image: gateway:1.0
    container_name: laokou-gateway
    environment:
      - TZ="Asia/Shanghai"
    restart: on-failure
    networks:
      - laokou
    ports:
      - "5555:5555"
    depends_on:
      - laokou-register-service
  laokou-register-service:
    image: register:1.0
    container_name: laokou-register
    environment:
      - TZ="Asia/Shanghai"
    networks:
      - laokou
    ports:
      - "1111:1111"
    restart: on-failure
  laokou-admin-service:
    image: admin:1.0
    container_name: laokou-admin
    environment:
      - TZ="Asia/Shanghai"
    networks:
      - laokou
    ports:
      - "9999:9999"
    restart: on-failure
    depends_on:
      - laokou-register-service
  laokou-auth-service:
    image: auth:1.0
    container_name: laokou-auth
    environment:
      - TZ="Asia/Shanghai"
    networks:
      - laokou
    ports:
      - "9000:9000"
    restart: on-failure
    depends_on:
      - laokou-register-service
  laokou-monitor-service:
    image: monitor:1.0
    container_name: laokou-monitor
    environment:
      - TZ="Asia/Shanghai"
    networks:
      - laokou
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - laokou-register-service
networks:
  laokou:
    driver: bridge
