spring:
  boot:
    # admin
    admin:
      client:
        url: http://127.0.0.1:5000/monitor
        username: root
        password: 123456
        instance:
          service-base-url: http://127.0.0.1:${server.port}
  data:
    # redis
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 6000ms #连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: -1 #连接池最大连接数（使用负值表示无极限）
          max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10 #连接池最大空闲连接
          min-idle: 5 #连接池最小空间连接

# log
logging:
  file:
    name: logs/${spring.application.name}/info.log