server:
  port: 9995
  address: 127.0.0.1
spring:
  kafka:
    bootstrap-servers: 192.168.62.137:9092
  cloud:
    stream:
      bindings:
        send-out-0:
          destination: laokou-topic
          content-type: application/json