server:
  port: 10006
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true
rocketmq:
  name-server: 192.168.62.144:9876
  # 生产者
  producer:
    group: laokou-producer-group

spring:
  redis:
    host: 124.222.196.51
    port: 6379
    password: ENC(AHdloD6Rp4bu9SYZJbO7bcwErNCQm43R1b4zh6x4B10=)
    timeout: 6000ms #连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示无极限）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空间连接