jasypt:
  encryptor:
    password: koushenhai5201314wumeihua

spring:
  profiles:
    active: @profile.active@
  application:
    name: laokou-rocketmq-consumer

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体类扫描，多个package用头号或分号分隔
  type-aliases-package: org.laokou.rocketmq.consumer.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl