spring:
  profiles:
    active: @profile.active@
  application:
    name: @artifactId@

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 10000 # 连接时间
        readTimeout: 15000 # 超时时间