# server
server:
  port: 9999
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true

# spring
spring:
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    tencent:
      metadata:
        content:
          env: @profile.active@
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: @mybatis-plus.log-impl@

# feign
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 120000
        readTimeout: 120000

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always