#spring
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: laokou-admin
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000