# tomcat
server:
  port: 5555
  tomcat:
    connection-timeout: 18000000
  # https配置
  ssl:
    enabled: true
    key-alias: gateway
    key-store-type: PKCS12
    key-store-password: koushenhai
    key-store: classpath:scg-keystore.p12

spring:
  profiles:
    active: @profile.active@
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

gateway:
  uris:
    - /oauth2/captcha
    - /oauth2/login
    - /actuator/**
    - /ws/**
    - /favicon.ico