# tomcat
server:
  port: 5555
  tomcat:
    connection-timeout: 600000
  compression:
    enabled: true

spring:
  profiles:
    active: @profile.active@
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
    # gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: laokou-admin
          uri: lb://laokou-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: laokou-auth
          uri: lb://laokou-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: laokou-elasticsearch
          uri: lb://laokou-elasticsearch
          predicates:
            - Path=/elasticsearch/**
          filters:
            - StripPrefix=1
        - id: laokou-rocketmq
          uri: lb://laokou-rocketmq
          predicates:
            - Path=/rocketmq/**
          filters:
            - StripPrefix=1
        - id: laokou-oss
          uri: lb://laokou-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: laokou-im
          uri: lb://laokou-im
          predicates:
            - Path=/im/**
          filters:
            - StripPrefix=1

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 忽略uris
ignore:
  uris:
    - /oauth2/captcha
    - /actuator/**
    - /ws/**
    - /favicon.ico