server:
  address: 127.0.0.1
  port: 5555
  tomcat:
    connection-timeout: 18000000

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示无极限）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空间连接
  boot:
    admin:
      client:
        url: http://127.0.0.1:5000/monitor
        username: root
        password: koushenhai
        instance:
          service-base-url: http://127.0.0.1:${server.port}
          prefer-ip: true

logging:
  file:
    name: logs/${spring.application.name}/info.log

app:
  id: gateway # 应用全局唯一的身份标识
apollo:
  cacheDir: config # 自定义本地配置文件缓存路径
  bootstrap:
    enabled: true # 设置在应用启动阶段就加载 Apollo 配置
    eagerLoad:
      enabled: true
