jasypt:
  encryptor:
    password: koushenhai5201314wumeihua
#spring
spring:
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: @pom.parent.artifactId@
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

#mybatis
mybatis-plus:
  configuration:
    log-impl: @mybatis-plus.log-impl@