#spring
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: @pom.parent.artifactId@
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    cache-enabled: false
    log-impl: @mybatis-plus.log-impl@

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 10000 # 连接时间
        readTimeout: 15000 # 超时时间