jasypt:
  encryptor:
    password: koushenhai5201314wumeihua

#spring
spring:
  security:
    user:
      name: root
      password: 123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: laokou-auth
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connectTimeout: 10000 # 连接时间
        readTimeout: 15000 # 超时时间