jasypt:
  encryptor:
    password: koushenhai5201314wumeihua
#spring
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: @pom.parent.artifactId@
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*