spring:
  cloud:
    gateway:
      routes:
        - id: laokou-admin
          uri: lb://laokou-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            # 限流
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 3000
            # 降级
            - name: CircuitBreaker
              args:
                name: default
                # 降级接口地址
                fallbackUri: 'forward:/fallback'
        - id: laokou-auth
          uri: lb://laokou-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            # 限流
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 3000
            # 降级
            - name: CircuitBreaker
              args:
                name: default
                # 降级接口地址
                fallbackUri: 'forward:/fallback'
        - id: laokou-elasticsearch
          uri: lb://laokou-elasticsearch
          predicates:
            - Path=/elasticsearch/**
          filters:
            - StripPrefix=1
            # 限流
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 3000
            # 降级
            - name: CircuitBreaker
              args:
                name: default
                # 降级接口地址
                fallbackUri: 'forward:/fallback'
        - id: laokou-kafka
          uri: lb://laokou-kafka
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
            # 限流
            - name: RequestRateLimiter #请求数限流
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 3000
            # 降级
            - name: CircuitBreaker
              args:
                name: default
                # 降级接口地址
                fallbackUri: 'forward:/fallback'